### ISSUE TITLE
Uwu mode

### ISSUE THREAD

**Issue by psethwick** [psethwick/plover_fancytext#9]

**Comment by elkowar** [comment]
I'm working on it!

**Comment by eepykate** [comment]
WHY DID YOU CAUSE THIS

WHAT HAVE YOU BROUGHT UPON THIS CURSED LAND

**Comment by eepykate** [comment]
Be aware that your actions will have consequences. You should not take fiddling with affairs this drastic so lightly.

**Comment by psethwick** [comment]
Rad, thanks @elkowar !
